version: '3'

services:
  test2-micro:
    build:
      context: ./test2-micro
      dockerfile: micro.dockerfile
    ports:
      - "50051:50051"

  test1-micro:
    build:
      context: ./test1-micro
      dockerfile: micro.dockerfile
    ports:
      - "8080:8080"
    environment:
      GRPC_SERVICE_ADDR: "test2-micro:50051"
